function [newData1] = importfile(fileToRead1,HEADERLINES)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 20-Oct-2020 13:54:54

DELIMITER = ' ';

% Import the file
newData1 = importdata(fileToRead1, DELIMITER, HEADERLINES);

